projects/uitdatabank/reference/entry.json

- Changed names & order of EntryAPI endpoints
---
Ticket: https://jira.uitdatabank.be/browse/III-4628
Branch on Stoplight: https://docs.publiq.be/docs/uitdatabank/branches/uitdatabank%2FIII-4628-clean-up-order-of-entry-api-endpoints/YXBpOjE3NTM4OTQw-entry-api

III-4628 Clean up order of EntryApi endpoints

---

projects/uitdatabank/models/event-attendanceMode-put.json
projects/uitdatabank/models/event-attendanceMode.json
projects/uitdatabank/models/event-location.json
projects/uitdatabank/models/event.json
projects/uitdatabank/reference/entry.json
projects/uitdatabank/toc.json

- Added docs for updating attendance mode
---
Ticket: https://jira.uitdatabank.be/III-4667

III-4667 Add docs for updating attendance mode

---

projects/uitdatabank/models/event-onlineUrl-put.json
projects/uitdatabank/models/event-onlineUrl.json
projects/uitdatabank/models/event.json
projects/uitdatabank/reference/entry.json

- Added model for `onlineUrl`
- Documented endpoint `PUT online-url` to update `onlineUrl`
- Documented endpoint `DELETE online-url` to delete `onlineUrl`
---
Ticket: https://jira.uitdatabank.be/III-4456

III-4456 Document onlineUrl and endpoint to update onlineUrl

---

.github/workflows/publish-api-design-guidelines.yml
.github/workflows/publish-authentication.yml
.github/workflows/publish-errors.yml
.github/workflows/publish-museumpassmusees.yml
.github/workflows/publish-uitdatabank.yml
.github/workflows/publish-widgets.yml
.github/workflows/split-udb3-json-schemas.yml
projects/api-design-guidelines/docs/introduction.md

- Changed the project-specific GitHub Actions to only run if a change is pushed to their project folder
---
Ticket: https://jira.uitdatabank.be/browse/API-71

API-71 Only push branches to Stoplight or udb3-json-schemas if relevant changes are pushed to github

---

projects/uitdatabank/reference/entry.json

- Renamed `virtual location` to `online location`
---
Ticket: https://jira.uitdatabank.be/browse/III-4724

III-4724 Rename virtual location to online location

---

projects/uitdatabank/reference/entry.json

- Fixed description of update name

Fix description of update name

---

projects/uitdatabank/models/common-priceInfo.json

- Added the rule about uniqueness of tarrif names  by language
---
Ticket: https://jira.uitdatabank.be/browse/III-4685

III-4685 update priceInfo unique name

---

projects/uitdatabank/reference/entry.json

- Changed status type / bookingAvailability to "Unavailable" on top level of event update example
---
Ticket: https://jira.uitdatabank.be/browse/III-4761

III-4761 Change status type / bookingAvailability to "Unavailable" on top level of event update example

---

README.md
projects/uitdatabank/docs/terminology.md
projects/uitpas/docs/introduction.md
projects/uitpas/docs/registering-events.md
projects/uitpas/docs/registering-ticket-sales.md
projects/uitpas/docs/searching-for-UiTPAS-events.md
projects/widgets/docs/demo.md
projects/widgets/toc.json

- [Added ...]
- [Changed ...]
- [Removed ...]
- [Fixed ...]
---
Ticket: https://jira.uitdatabank.be/browse/...

Add demo page

---

projects/uitpas/reference/uitpas.json

Removed internal=true from Reward (except GET /rewards) and Cardsystem endpoints

publish new UPS endpoints

---

projects/uitpas/reference/uitpas.json

- corrected array params
---
Ticket: https://jira.uitdatabank.be/browse/UPS-3610

UPS-3610 array params in Reward search

---

projects/uitpas/docs/faq.md

- Fixed casing in UiTinVlaanderen link and URL

Don't mix product name UiTinVlaanderen and URL uitinvlaanderen.be

---

projects/authentication/docs/methods.md

- Added an overview of the supported authentication methods per API, to make it more clear at a glance which authentication method is relevant for an integrator who's reading the authentication docs.
- Slightly optimized some wording of the sentences in the touched file.
---
Ticket: https://jira.uitdatabank.be/browse/API-89

API-89 Document overview of supported authentication methods per API

---

projects/uitpas/reference/uitpas.json

- Set reward search to internal: false
---
Ticket: https://jira.uitdatabank.be/browse/UPS-3610

UPS-3610 publish reward search

---

projects/authentication/docs/user-access-token.md

- Documentation about refresh tokens to user access tokens guide
---
Ticket: https://jira.uitdatabank.be/browse/API-93
Note: This continues on the work from #59 so I've pointed this PR to that one until it is merged into `main`. So #59 should be reviewed/approved/merged before this.

API-93 Document how refresh tokens work

---

projects/authentication/docs/client-access-token.md
projects/authentication/docs/client-identification.md
projects/authentication/docs/user-access-token.md

- Added info block with links to overview on specific auth method pages
---
Ticket: https://jira.uitdatabank.be/browse/API-92
~Note: #60 should be reviewed & merged first.~

API-92 Add links to overview

---

projects/authentication/docs/client-access-token.md
projects/authentication/docs/environments.md
projects/authentication/docs/user-access-token.md
projects/authentication/toc.json

- Page about the test and production environments
- Guides about user access tokens and client access tokens refer to the separate page about authorization server URLs
---
Ticket: https://jira.uitdatabank.be/browse/API-55

API-55 Document different environments

---

projects/authentication/docs/errors.md
projects/authentication/toc.json

- Clarified the page title for authentication errors and the intro text and some details
---
Ticket: https://jira.uitdatabank.be/browse/API-41

API-41 Clarify error docs for authentication

---

projects/authentication/docs/user-access-token.md

- Documentation how to implement logout functionality
---
Ticket: https://jira.uitdatabank.be/browse/API-39
Note: This continues from #66 , so that must be reviewed and merged before this one! ⚠️

API-39 Document logout functionality

---

projects/authentication/toc.json

- Added slugs for pretty URLs in authentication project
---
Ticket: https://jira.uitdatabank.be/browse/API-95

API-95 Use slugs for pretty URLs

---

projects/uitpas/reference/uitpas.json

- allow all security schemes on uitid/emails instead of explicit documentation of x-client-id

allow all security schemes on uitpas uitid/emails

---

projects/uitdatabank/models/place-availableFrom-put.json

- Typo in `place-availableFrom-put`

uitdatabank - typo in place-availableFrom-put

---

projects/authentication/docs/methods.md
projects/authentication/docs/user-access-token.md
projects/authentication/toc.json

- Clearly mention UiTID (more) in documentation about user access tokens
---
Ticket: https://jira.uitdatabank.be/browse/API-97

API-97 Login with UiTID

---

projects/uitdatabank/models/event-description-put.json
projects/uitdatabank/models/place-description-put.json

- schemas to validate event and place description update
---
Ticket: https://jira.uitdatabank.be/browse/III-4251

Uitdatabank - Add schema to validate event and place description endpoint

---

projects/uitdatabank/toc.json

- Changed the UiTdatabank sidebar structure to group everything related to 1 API together
---
Screenshot:

UiTdatabank: Update sidebar to group everything related to 1 API together

---

projects/uitdatabank/models/event-image-put.json
projects/uitdatabank/models/organizer-image-post.json
projects/uitdatabank/models/place-image-put.json

- schema to validate event and place image update endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4258

Uitdatabank - Add schema to validate event and place image update endpoint

---

projects/uitdatabank/models/event-main-image-put.json
projects/uitdatabank/models/place-main-image-put.json

- schema to validate event and place set main image endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4260

Uitdatabank - Add schema to validate event and place set main image endpoint

---

projects/uitpas/reference/uitpas.json

UiTPAS Checkin endpoint
---
Ticket: https://jira.uitdatabank.be/browse/UPS-3772

UPS-3772 checkin endpoint

---

projects/uitpas/reference/uitpas.json

- Fixed location to Error.json

correct error location

---

projects/uitpas/reference/uitpas.json

separate tag for current passholder endpoints

separate tag for current passholder endpoints

---

projects/uitdatabank/docs/terms.md

* Basics about the categorisation model
* Facility definitions
Ticket: https://jira.uitdatabank.be/browse/III-5026

Basics of the categorisation model & facility definitions

---

projects/uitdatabank/docs/errors.md

- Documentation on why an image cannot be set as the main image on an event/place
---
Ticket: https://jira.uitdatabank.be/browse/III-4260

Document error when selecting the main image on an event/place

---

projects/uitdatabank/models/event-contactPoint-put.json
projects/uitdatabank/models/place-contactPoint-put.json

- Add schema to validate event and place update contactPoint endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4263

Uitdatabank - Add schema to validate event and place update contactPoint endpoint

---

projects/uitdatabank/docs/errors.md
projects/uitdatabank/docs/search-api/advanced-queries.md

One more missing language property in a field name

Add language property to field name

---

projects/uitdatabank/models/event-typicalAgeRange-put.json
projects/uitdatabank/models/place-typicalAgeRange-put.json

-  Schema to validate event and place update typicalAgeRange endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III4269

Uitdatabank - Add schema to validate event and place update typicalAgeRange endpoint

---

projects/uitdatabank/docs/entry-api/reuse-places-organizers.md

Wording so that it is consistent across the entire page

Correct wording

---

projects/uitpas/reference/uitpas.json

Transaction history endpoint
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4171

UPS-4171 transaction history endpoint

---

projects/authentication/docs/methods.md

- Added link to SAPI3 API docs in overview of supported authentication methods per API

UiTdatabank: Link to SAPI3 docs in auth overview

---

projects/uitdatabank/models/place-address-put.json

- schema to validate place update address endpoint.
---
Ticket: https://jira.uitdatabank.be/browse/III-4276

Uitdatabank - Add schema to validate place update address endpoint

---

projects/uitdatabank/reference/entry.json

- Added documentation for endpoints to delete an image from an event/place
---
Ticket: https://jira.uitdatabank.be/browse/III-4259

UiTdatabank III-4259 Document "delete image from event/place" endpoints

---

projects/uitdatabank/reference/entry.json

- Added documentation for endpoints to remove label from an event/place
---
Ticket: https://jira.uitdatabank.be/browse/III-4265

UiTdatabank III-4265 Document delete label from offer endpoints

---

projects/uitdatabank/docs/search-api/advanced-queries.md

Missing parameters:
* `location.labels`
* `organizer.labels`

Document missing advanced query fields

---

projects/uitdatabank/models/event-workflowStatus-put.json
projects/uitdatabank/models/place-workflowStatus-put.json
projects/uitdatabank/reference/entry.json

- Added documentation for the new workflow status endpoints from https://jira.uitdatabank.be/browse/III-4272
---
Ticket: https://jira.uitdatabank.be/browse/III-5106

UiTdatabank III-5106 Document workflow status endpoints

---

projects/uitdatabank/docs/entry-api/reuse-places-organizers.md

- Added documentation how to find & re-use existing places without a UI for users that enter event data
- Added a warning to existing documentation about how to find & re-use existing organizers without a UI for users that enter event data

UiTdatabank: Document how to reuse places without UI

---

projects/uitdatabank/reference/entry.json

- Documentation for `events/{eventId}/labels/{labelName}`
- Documentation for `places/{eventId}/labels/{labelName}`
---
Ticket: https://jira.uitdatabank.be/browse/III-4264

Uitdatabank - offer labels add

---

projects/uitdatabank/reference/entry.json

- Documentation for PUT `/events/{eventId}/booking-info`.
- Documentation for PUT `/events/{eventId}/booking-info`.
---
Ticket: https://jira.uitdatabank.be/browse/III-5046

Uitdatabank - document offer bookingInfo put

---

projects/uitdatabank/reference/entry.json

- Documentation for PUT `/events/{eventId}/contact-point`
- Documentation for PUT `/places/{placeId}/contact-point` 
---
Ticket: https://jira.uitdatabank.be/browse/III-5051

Uitdatabank - offer contact point put

---

projects/uitdatabank/reference/entry.json

- Documentation for PUT `/places/{placeId}/address/{language}`
---
Ticket: https://jira.uitdatabank.be/browse/III-5054

Uitdatabank - place address put

---

projects/uitdatabank/reference/entry.json

- Documentation for PUT and DELETE `/events/{eventId}/typical-age-range`
- Documentation for PUT and DELETE `/places/{placeId}/typical-age-range`
---
Ticket: https://jira.uitdatabank.be/browse/III-5052

Uitdatabank - offer typical age range

---

projects/uitdatabank/reference/entry.json

- Documentation for PUT and DELETE on `events/{eventId}/organizer/{organizerId}`
- Documentation for PUT and DELETE on `places/{placeId}/organizer/{organizerId}`
---
Ticket: https://jira.uitdatabank.be/browse/III-4266 and https://jira.uitdatabank.be/browse/III-4267

Uitdatabank - offer organizer put and delete

---

projects/uitdatabank/reference/entry.json

- Documentation for PUT `/events/{eventId}/description/{language}`
- Documentation for PUT `/places/{placeId}/description/{language}`
---
Ticket: https://jira.uitdatabank.be/browse/III-5047

Uitdatabank - offer description put

---

projects/uitdatabank/reference/entry.json

- Documentation for GET `/user`
---
Ticket: https://jira.uitdatabank.be/browse/III-5101

Uitdatabank - Add documentation for GET `/user`

---

projects/widgets/docs/geavanceerde-instellingen.md
projects/widgets/docs/taalinstellingen.md

- Some automatic changes by the linter. The linting check was green already, but these small quirks are still changed by the linter when running the fixer.

Widgets: Linting™

---

projects/uitdatabank/docs/entry-api/requirements-before-going-live.md

- Minor tweaks and fixes in the "Requirements before going live" guide

UiTdatabank: Content checklist tweaks

---

projects/widgets/docs/configureren/html.md

Documentation page about uploading images
Video link will be added later on in a follow up PR together with all the other video links

Add documentation about uploading images in widgets

---

projects/widgets/docs/aan-de-slag.md
projects/widgets/docs/configureren/html.md
projects/widgets/docs/inleiding.md
projects/widgets/docs/linken-van-artikels-aan-events.md
projects/widgets/docs/publiceren-en-embedden-op-je-website.md
projects/widgets/docs/rijen-en-blokken.md
projects/widgets/docs/templates.md

* Minor copy changes 
* Correct typo's

Fix and polish copy

---

projects/widgets/docs/inleiding.md
projects/widgets/docs/templates.md

* check mark icons into cross mark emoji
* typo `vetrekken` -> `vertrekken`

Process feedback from Karen

---

projects/uitdatabank/docs/search-api/getting-started.md
projects/uitdatabank/toc.json

- Added a "Getting started" page for Search API, to give an overview of how it works and how to make requests and next steps
---
Note: This branches from #187 to avoid merge conflicts with the menu changes

III-5108 Search API "Getting started"

---

projects/widgets/docs/inleiding.md

- Changed the structure so that it is consistent with the one of UiTdatabank & UiTPAS
- Typo

Fix typo & change structure

---

projects/widgets/docs/linken-van-artikels-aan-events.md

* dead link to UiTinVlaanderen detail page

Remove dead link

---

projects/uitdatabank/docs/entry-api/events/create.md
projects/uitdatabank/docs/entry-api/events/update.md

- Guide about updating events
- Warning in create guide about adding users as contributors if they need to be able to edit the events later
---

III-5108 Guide about updating events

---

projects/uitdatabank/docs/entry-api/events/delete.md

- Added guide about deleting an event
---

III-5108 Add guide about deleting an event

---

projects/uitdatabank/docs/entry-api/shared/calendar-info.md

- Added guide about calendar properties
---

III-5108 Add guide about calendar info

---

projects/uitdatabank/docs/entry-api/shared/description.md

- Added guide about description property
---

III-5108 description

---

projects/uitdatabank/docs/entry-api/events/publish.md

- Fixed broken link on "Publishing an event" guide
---

III-5108 Fix broken link on publish guide

---

projects/uitpas/reference/uitpas.json

- clarified names and descriptions in passes endpoints
- included social tariff and firstName in passes responses
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4098

UPS-4098 passes

---

projects/uitdatabank/docs/entry-api/shared/contributors.md

- Guide about contributors
---
Note: This is still under development (but for the biggest part already ready for deploy), but we can already merge this page in the meantime and just wait to publish the docs  until the new endpoints are deployed. And these docs are not actively used yet in a large scale anyway.

III-5108 Add guide about contributors

---

projects/uitdatabank/models/common-contributors.json

- Change minimum number of `contributors` from `1` to `0` (needed to delete all `contributors`)
---
Ticket: https://jira.uitdatabank.be/browse/III-5214

III-5214 Set minimum nr of contributors to 0

---

projects/uitdatabank/reference/search.json

- `id` as Search Parameter for `Organizer`
---
Ticket: https://jira.uitdatabank.be/browse/III-4590

III-4590 Add `id` as `Organizer` search param

---

projects/uitdatabank/models/common-newsArticle-image.json
projects/uitdatabank/models/common-string-uri-image.json
projects/uitdatabank/models/newsArticle-post.json
projects/uitdatabank/models/newsArticle.json

- `common-string-uri-image.json` for image `URI`
- `common-newsArticle-image.json` 
- Added `common-newsArticle-image.json` to `newsArticle-post.json`
- - Added `common-newsArticle-image.json` to `newsArticle.json`
---
Ticket: https://jira.uitdatabank.be/browse/III-5166

III-5166 add Image to newsArticle

---

projects/uitpas/reference/uitpas.json

* added isRedeemableBy query param on GET /rewards
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4145

UPS-4145 (re)introduce isRedeemableBy

---

projects/uitdatabank/docs/search-api/advanced-queries.md
projects/uitdatabank/reference/search.json

* Contributors to the Search API reference
* Contributors as an advanced query parameter

Document `contributors` parameters

---

projects/api-design-guidelines/docs/sorting.md
projects/uitpas/reference/uitpas.json

- introduced new sort parameter
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4382

UPS-4382 new sort proposal

---

projects/uitpas/reference/uitpas.json

- added permissions array to GET /permissions response
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4099

UPS-4099 added permissions to GET /permissions

---

projects/uitpas/reference/uitpas.json

- default type POINTS in reward search
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4419

UPS-4419 default type POINTS in reward search

---

projects/uitpas/reference/uitpas.json

- added missing permission
- renamed permissions for consistency 
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4099

UPS-4099 fix permission names

---

projects/uitpas/reference/uitpas.json

- documented missing errors in get redeem status
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4375

UPS-4375 document missing errors

---

projects/uitpas/toc.json

- Added errors page to toc
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4377

UPS-4377 added errors to toc

---

projects/uitdatabank/docs/entry-api/places/update.md

- Guide about updating places
---
Ticket: https://jira.uitdatabank.be/browse/III-5452

III-5452 Add guides about updating places

---

projects/api-design-guidelines/docs/sorting.md
projects/uitdatabank/docs/entry-api/events/booking-availability.md
projects/uitdatabank/docs/entry-api/events/create-school.md
projects/uitdatabank/docs/entry-api/events/delete.md
projects/uitdatabank/docs/entry-api/events/publish.md
projects/uitdatabank/docs/entry-api/events/status.md
projects/uitdatabank/docs/entry-api/events/update.md
projects/uitdatabank/docs/entry-api/places/publish.md
projects/uitdatabank/docs/entry-api/shared/calendar-info.md
projects/uitdatabank/docs/entry-api/shared/contributors.md
projects/uitdatabank/docs/entry-api/shared/description.md
projects/uitdatabank/docs/entry-api/shared/images.md

- Guide about publishing places
---
Ticket: https://jira.uitdatabank.be/browse/III-5450

III-5450 Add guide about publishing places

---

projects/uitdatabank/docs/entry-api/places/delete.md

- Guide about deleting a place
---
Ticket: https://jira.uitdatabank.be/browse/III-5449

III-5449 Add guide about deleting a place

---

projects/uitdatabank/docs/entry-api/organizers/delete.md

- Guide about deleting `organizers`
---
Ticket: https://jira.uitdatabank.be/browse/III-5443

uitdatabank/III-5443 Deleting Organizers

---

projects/uitdatabank/docs/entry-api/organizers/linking.md

- Guide about linking an `organizer` to an `event` or `place`
---
Ticket: https://jira.uitdatabank.be/browse/III-5444

III-5444 linking organizers to offers

---

.github/ISSUE_TEMPLATE/new-project.md
README.md

- Changed default assignee for new issues to request a new Stoplight project to @JonasVHG

Change new stoplight project request assignee

---

projects/uitdatabank/models/event-contributors.json
projects/uitdatabank/models/event-with-read-example.json
projects/uitdatabank/models/event.json
projects/uitdatabank/models/organizer-contributors.json
projects/uitdatabank/models/organizer-with-read-example.json
projects/uitdatabank/models/organizer.contributors.json
projects/uitdatabank/models/organizer.json
projects/uitdatabank/models/place-contributors.json
projects/uitdatabank/models/place-with-read-example.json
projects/uitdatabank/models/place.json

- contributors property on event model
- contributors property on place model
- contributors property on organizer model
---
Ticket: https://jira.uitdatabank.be/browse/III-5469

III-5649 document missing contributors property

---

projects/uitpas/reference/uitpas.json

- clarified PUT rewards documentation
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4437

UPS-4437 clarify PUT rewards documentation

---

projects/uitpas/reference/uitpas.json

* added isInterestingForPassholderId to reward search
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4376

UPS-4376 added isInterestingForPassholderId to reward search

---

projects/uitdatabank/models/production.json
projects/uitdatabank/reference/entry.json

- linting error caused by errors in `production.json`
- Use correct format in for `production.json` so it is identical to `GET` https://io.uitdatabank.be/productions
---
Ticket: https://jira.uitdatabank.be/browse/III-5556

III-5556: fix linting error

---

projects/uitdatabank/docs/entry-api/organizers/update.md

- Guide about updating `Organizers`
---
Ticket: https://jira.uitdatabank.be/browse/III-5446

III-5446 updating organizers

---

projects/uitdatabank/docs/entry-api/organizers/publish.md

- Added guide about publishing `organizers` & their `WorkflowStatus`
- 
---
Ticket: https://jira.uitdatabank.be/browse/III-5445

III-5445 guide about publishing organizers

---

projects/uitdatabank/docs/entry-api/places/booking-availability.md

- info block about impossibility to update the bookingAvailability for places
---
Ticket: https://jira.uitdatabank.be/browse/III-5447

III-5447 bookingAvailability for places

---

projects/uitdatabank/docs/exceptions.md
projects/uitdatabank/toc.json

- Documentation page about exceptions when using the UiTdatabank API 
---
Ticket: https://jira.uitdatabank.be/browse/III-5533

III-5533 Exceptions

---

projects/uitdatabank/docs/entry-api/events/status.md
projects/uitdatabank/docs/entry-api/places/status.md

- Documentation page about how to mark a place as (temporarily) closed
- Typo in documentation about how to postpone or cancel events
---
Ticket: https://jira.uitdatabank.be/browse/III-5451

III-5451 Marking a place as closed

---

projects/uitdatabank/docs/search-api/advanced/boosting.md

Copy paste mistakes / typos
---

Fix copy paste error

---

projects/uitdatabank/docs/entry-api/shared/videos.md

- Added guide about Videos.
---
Ticket: https://jira.uitdatabank.be/browse/III-5457

III-5457 guide about videos

---

projects/uitdatabank/docs/search-api/advanced/advanced-queries.md

- linting errors in file `advanced-queries.md`
---

HOTFIX: Fix linting errors

---

projects/uitdatabank/docs/search-api/advanced/advanced-queries.md

- broken links in advanced query guide

Fix broken links in advanced query guide

---

projects/uitpas/reference/uitpas.json

- endUserMessage in GET /tariffs response
- removed REWARD type in Tariff + examples
---
Ticket: https://jira.uitdatabank.be/browse/ups-3785

UPS-3785 endUserMessage in tariffs

---

projects/uitpas/reference/uitpas.json

- static tariff endpoint
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4517

UPS-4517 static tariff

---

projects/widgets/docs/gebruiksvoorwaarden.md
projects/widgets/toc.json

- Terms of use to widget docs
❗Disclaimer: I added the terms of use "as is". They will need to be reformulated / updated in order to be in sync with the current application landscape and authentication methods

Terms of use for widgets

---

projects/widgets/docs/configureren/tips.md

- Documentation about defining the content scope of a tips widget

How-to define the content scope of a tips widget

---

projects/uitdatabank/models/common-string-uri-video.json
projects/uitdatabank/models/common-videos.json

Added the possibility of Youtube shorts as attachment for events
---
Ticket: https://jira.uitdatabank.be/browse/III-5624

Added the possibility of Youtube shorts as attachment for events

---

projects/uitdatabank/docs/entry-api/shared/workflow-status.md
projects/uitdatabank/docs/terminology.md
projects/widgets/docs/configureren/tips.md
projects/widgets/docs/gebruiksvoorwaarden.md

- Terminology
- Sorting
---
Ticket: https://jira.uitdatabank.be/browse/III-5736

Add terminology & sort alphabetically

---

projects/uitdatabank/docs/terminology.md
projects/uitdatabank/reference/entry.json

- documentation for `PUT /events/:eventId/status`
- documentation for `PUT /places/:placeId/status`
---
Ticket: https://jira.uitdatabank.be/browse/III-5383

III-5383 Status update

---

projects/uitdatabank/docs/terminology.md
projects/uitdatabank/models/production-eventIds.json
projects/uitdatabank/models/productions-skip.json
projects/uitdatabank/reference/entry.json

- Add documentation about how to skip a pair of suggested events
---
Ticket: https://jira.uitdatabank.be/browse/III-5555

III-5555 Skip production pair

---

projects/uitdatabank/docs/terminology.md
projects/uitdatabank/models/event-@id.json
projects/uitdatabank/models/organizer-@id.json
projects/uitdatabank/models/place-@id.json
projects/uitdatabank/reference/search.json

Fix broken links in event model

---

projects/uitdatabank/models/organizer-educationalDescription.json
projects/uitdatabank/models/organizer.json

- Added educational description to organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-5757

III-5757 Add educational description to organizer

---

projects/uitdatabank/models/common-string-uri.json

- reverted the regex for a uri back to the old one, because of problems.
---

UiTDatabank: revert regex to avoid problems.

---

projects/uitdatabank/docs/terminology.md
projects/uitdatabank/reference/entry.json

- Documentation about how to add a single event to an existing production 
---
Ticket: https://jira.uitdatabank.be/browse/III-5558

III-5558 Add single event to Production

---

projects/uitdatabank/reference/entry.json

Added delete description endpoint for place and event
Ticket: https://jira.uitdatabank.be/browse/III-4520

Added delete description endpoint for place and event

---

projects/uitdatabank/models/organizer-educational-description-put.json
projects/uitdatabank/models/organizer-educationalDescription.json
projects/uitdatabank/reference/entry.json

- `models/organizer-educational-description-put.json`
- `entry.json`: Added `PUT`-endpoint to add `educationalDescription`
- `models/organizer-educationalDescription.json`: fixed title
---
Ticket: https://jira.uitdatabank.be/browse/III-5755

III-5755: add put endpoint educationalDescription

---

projects/uitdatabank/reference/entry.json

Provide endpoint to delete educational description on organiser
- Description to update educational description said it changed the normal description.
---
Ticket: https://jira.uitdatabank.be/browse/III-5756

Provide endpoint to delete educational description on organiser

---

projects/uitpas/reference/uitpas.json

- Added search passholders by uitidId
- Added PASSHOLDERS_SEARCH_ALL permission
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4582

uitpas: search passholders by uitidId

---

projects/uitdatabank/docs/terminology.md
projects/uitdatabank/models/production-eventIds.json
projects/uitdatabank/models/production-name.json
projects/uitdatabank/models/production-post.json
projects/uitdatabank/reference/entry.json

- Documentation on how to create a production
---
Ticket: https://jira.uitdatabank.be/browse/III-5557

III-5557 Create production

---

projects/uitdatabank/docs/terminology.md
projects/uitdatabank/reference/entry.json

Documentation about how to merge 2 productions into 1
---
Ticket: https://jira.uitdatabank.be/browse/III-5559

III-5559 Merge productions

---

projects/uitdatabank/docs/search-api/filters/age.md
projects/uitdatabank/docs/search-api/filters/labels.md
projects/uitdatabank/docs/search-api/filters/terms.md
projects/uitdatabank/docs/search-api/filters/uitpas.md
projects/uitpas/docs/registering-ticket-sales.md
projects/uitpas/docs/user-friendly-error-messages.md

- Documentation page about filtering on terms
---
Ticket: https://jira.uitdatabank.be/browse/III-5465

III-5465 Filtering on terms

---

projects/uitdatabank/docs/search-api/filters/freetext.md

- Documentation page on free text search
---
Ticket: https://jira.uitdatabank.be/browse/III-5461

III-5461 Free text search

---

projects/uitdatabank/docs/terms-of-use/terms-of-use.md
projects/uitdatabank/toc.json

- terms of use (dutch)
---
Ticket: https://jira.uitdatabank.be/browse/III-5531

III-5531 Terms of use

---

projects/uitdatabank/docs/entry-api/shared/images.md
projects/uitdatabank/reference/entry.json

- reference of the `GET` endpoint of `images`
- Added info/link of the `GET` endpoint to the shared property `Image`
---
Ticket: https://jira.uitdatabank.be/browse/III-5468

III-5468 Get image Endpoint

---

projects/uitdatabank/models/event.json
projects/uitdatabank/models/organizer.json
projects/uitdatabank/models/place.json

- Added "what are event" guide to event model page
---
Ticket: https://jira.uitdatabank.be/browse/III-5470

WIP III-5470 Added what are guide to event

---

projects/release-notes/spectral.yaml

- spectral.yaml file (just like for the other projects)

Add spectral.yaml

---

projects/release-notes/docs/introduction.md
projects/release-notes/docs/uitdatabank/2020.md
projects/release-notes/docs/uitdatabank/2021.md
projects/release-notes/docs/uitdatabank/2022.md
projects/release-notes/docs/uitdatabank/2023.md
projects/release-notes/docs/uitpas/2023.md
projects/release-notes/docs/widgets/2020.md
projects/release-notes/docs/widgets/2021.md
projects/release-notes/docs/widgets/2022.md
projects/release-notes/docs/widgets/2023.md
projects/release-notes/toc.json

* UDB 2020, 2021 2022 release notes
* Styling
* Broken table of contents

Changelog optimizations

---

projects/release-notes/toc.json

- Introduction being absent from sidebar / table of contents
---
Ticket: https://jira.uitdatabank.be/browse/PPF-50

Add introduction to sidebar

---

projects/errors/models/Error.json
projects/uitdatabank/reference/entry.json

- Response bodies not being publicly visible
---
Ticket: https://jira.uitdatabank.be/browse/III-5872

Make response bodies for creating events public / visible

---

projects/uitdatabank/reference/search.json

- Security sections for Search API
---
Ticket: https://jira.uitdatabank.be/browse/III-5867

Add security sections

---

projects/uitpas/reference/uitpas.json

- UPS-4629 temporary download link endpoint
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4629

UPS-4629 temporary download link endpoint

---

projects/uitpas/reference/uitpas.json

- UPS-4669 allow transaction history for family members
- UPS-4667 allow check-in for family members
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4669
Ticket: https://jira.uitdatabank.be/browse/UPS-4667

UP-4618 family members

---

projects/uitdatabank/docs/entry-api/shared/price-info.md
projects/uitdatabank/reference/entry.json

- Added examples on PUT /events/:eventId/price-info
- Added examples on PUT /place/:placeId/price-info
- Added extra page on price info structure
---
Ticket: https://jira.uitdatabank.be/browse/III-5455

Write Entry API guide about price info

---

projects/uitdatabank/reference/entry.json

- incorrect alert about DELETE method not supported
---
Ticket: https://jira.uitdatabank.be/browse/III-5922

Remove incorrect alert about DELETE method not supported

---

projects/uitpas/reference/uitpas.json

UPS-4743 volledige passholder teruggeven in family-members
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4743

UPS-4743 volledige passholder teruggeven in family-members

---

projects/release-notes/docs/uitdatabank/2023.md

- release notes for deploy of new design and new organizer entry form
---
Ticket: https://jira.publiq.be/browse/III-5938

Add release notes for deploy of 01/12/2023

---

projects/uitpas/reference/uitpas.json

- clarify permission needed to delete family member
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4665

UPS-4665 clarify permission needed to delete family member

---

projects/uitpas/docs/test-dataset.md

- replaced "unused" UiTPAS number with on that was still unused.

Replace faulty test-account with new value

---

projects/widgets/docs/configureren/zoekresultaten.md

- Documentation about how to activate UiTX
---
Ticket: https://jira.uitdatabank.be/browse/WID-548

Add documentation about activation of uitx

---

projects/release-notes/docs/widgets/2024.md
projects/release-notes/toc.json
projects/uitdatabank/docs/entry-api/shared/price-info.md

- Side bar so that 2024 release notes are now also included
---

Fix side bar

---

projects/release-notes/docs/uitdatabank/2024.md
projects/release-notes/docs/widgets/2024.md

- Release notes for fixversion of 2024-02-07 and 2024-01-30
- Incorrect heading
- Typo

Release notes 2024-02-07

---

projects/uitdatabank/docs/entry-api/events/create-uitpas.md

- Link to docs on how to enable / disable specific cardsystems on an individual event
---
Ticket: https://jira.uitdatabank.be/browse/III-5441

Link to docs on how to enable / disable cardsystems

---

projects/api-design-guidelines/docs/rest.md
projects/uitdatabank/docs/search-api/advanced/advanced-queries.md

- `contributors` field
---
Ticket: https://jira.uitdatabank.be/browse/III-6054

Remove `contributors` field

---

projects/api-design-guidelines/docs/rest.md
projects/uitdatabank/docs/search-api/sorting.md

- Added paragraph for completeness sorting
---
Ticket: https://jira.uitdatabank.be/browse/III-6036

III-6036 Add paragraph for completeness sorting

---

projects/release-notes/docs/uitdatabank/2024.md

- Release notes for release of 15/02/2024

Release notes 2024-02-15

---

projects/uitdatabank/models/common-completeness.json
projects/uitdatabank/models/event.json
projects/uitdatabank/models/organizer.json
projects/uitdatabank/models/place.json

- Added completeness to JSON projections
---
Ticket: https://jira.uitdatabank.be/browse/III-6048

III-6048 Add completeness to JSON projections

---

projects/uitdatabank/docs/search-api/filters/default-filters.md

- [Fix typo](https://github.com/cultuurnet/apidocs/commit/b151258ac73b7f43a0fb7db2bb7a1980e25ac3cf)
`disbableDefaultFilters` -> `disableDefaultFilters`

Fix typo: disbableDefaultFilters -> disableDefaultFilters

---

projects/release-notes/docs/widgets/2024.md

- Release notes for fixversion 20240228

Release notes fixversion 2024-02-28

---

projects/uitdatabank/docs/errors.md
projects/uitdatabank/reference/entry.json

Improved error of duplicated places
---
Ticket: https://jira.uitdatabank.be/browse/III-6115

III-6115 Improve error duplicate places

---

projects/release-notes/docs/uitdatabank/2024.md

- release notes for fixversion 20240328

Release notes fixversion 2024-03-28

---

projects/uitdatabank/models/ownership-post.json

-  Added missing body example for creating an ownership request
---
Ticket: https://jira.uitdatabank.be/browse/III-6069

III-6069 Add missing body example

---

projects/widgets/docs/inleiding.md

- old widget image
---
Ticket: https://jira.uitdatabank.be/browse/PPF-372

Remove old widget image

---

projects/uitdatabank/models/common-name-localized.json
projects/uitdatabank/models/common-title.json
projects/uitdatabank/models/event-name.json
projects/uitdatabank/models/organizer-name.json
projects/uitdatabank/models/place-name.json

DO NOT MERGE YET - This also needs work on the frontend or users are going to get confusing error messages.
- III-5912 Limited name/title to 90 chars
Related to pr: https://github.com/cultuurnet/udb3-backend/pull/1625
---
Ticket: https://jira.uitdatabank.be/browse/III-5912

III-5912 Limited name/title to 90 chars

---

projects/uitdatabank/reference/entry.json

Change the endpoint of mailinglist to use kebab-case instead of camelCase.
---
Ticket: https://jira.uitdatabank.be/browse/III-6162

III-6162 Change the endpoint of mailinglist to use kebab-case instead of camelCase

---

projects/api-design-guidelines/docs/http-examples.md

Fix dead urls

---

projects/api-design-guidelines/docs/http-examples.md
projects/authentication/docs/requesting-credentials.md

- Copy about registering an integration 
- Link projectaanvraag --> publiq platform
---
Ticket: https://jira.uitdatabank.be/browse/PPF-419

Update copy and replace link to publiq platform

---

projects/uitpas/reference/uitpas.json

- Permission management endpoints
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5065

UPS-5065 permission management endpoints

---

projects/uitpas/docs/test-dataset.md

- chip numbers to UiTPAS cards
- online advantage
- expired welcome and points advantage
Ticket: UPS-5130

UPS - added test data

---

projects/uitpas/docs/quickstart.md

Update quickstart.md with new flow publiq platform

Update quickstart.md with new flow publiq platform

---

projects/authentication/docs/requesting-credentials.md
projects/release-notes/docs/uitdatabank/2024.md
projects/release-notes/docs/widgets/2024.md
projects/uitdatabank/docs/entry-api/shared/labels.md
projects/uitdatabank/docs/search-api/advanced/advanced-queries.md
projects/uitdatabank/docs/search-api/authentication.md
projects/uitdatabank/docs/search-api/filters/booking-availability.md
projects/uitdatabank/docs/search-api/filters/default-filters.md
projects/uitdatabank/docs/search-api/filters/status.md
projects/uitdatabank/toc.json
projects/uitpas/docs/getting-started.md
projects/uitpas/docs/registering-events.md
projects/uitpas/docs/test-dataset.md

* guide about filtering on `status`
* guide about filtering on `bookingAvailability`
---
Ticket: https://jira.uitdatabank.be/browse/PPF-548
Ticket: https://jira.uitdatabank.be/browse/PPF-549

PPF-548 | PPF-549 Filtering on `status` and `bookingAvailability`

---

projects/uitdatabank/docs/search-api/getting-started.md

Fix copy button

---

projects/release-notes/docs/uitdatabank/2024.md

* Release notes for the past months

Add new release notes

---

projects/uitdatabank/docs/search-api/filters/datetime.md

- Guide about filtering on time
---
Ticket: https://jira.uitdatabank.be/browse/PPF-551

PPF-551 Guide about filtering on time

---

projects/uitdatabank/models/common-string-uri-image.json

- Fixed image regex and allow jpg
---
Ticket: https://jira.uitdatabank.be/browse/III-6312

III-6312 Fix image regex and allow jpg

---

projects/uitdatabank/models/ownership-post.json

- Added possiblity to use ownerEmail to ownership request
---
Related to https://github.com/cultuurnet/udb3-backend/pull/1850
Ticket: https://jira.publiq.be/browse/PPF-632

Added possiblity to use ownerEmail to ownership request

---

projects/authentication/docs/user-access-token.md

- PK-41 tweaked auth docs
---
Ticket: https://jira.uitdatabank.be/browse/PK-41

PK-41 tweak auth docs

---

projects/uitdatabank/reference/entry.json

- Added DELETE ownership endpoint documentation
---
Ticket: https://jira.publiq.be/browse/III-6350

Added DELETE ownership endpoint documentation

---

projects/uitdatabank/reference/entry.json

- Added documentation for approve/reject ownership endpoints 
---
Ticket: https://jira.publiq.be/browse/III-6352 and https://jira.publiq.be/browse/III-6353

Added documentation for approve/reject ownership endpoints 

---

projects/uitpas/reference/uitpas.json

- Endpoint to retrieve the QR checkincode 
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4849

UPS-4849 qr checkincodes as download link

---

projects/uitpas/reference/uitpas.json

-  documented extra permissions
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4849

UPS-4849 document extra permissions

---

projects/api-design-guidelines/docs/rest.md
projects/uitpas/reference/uitpas.json

- document max limit value exceeded on all endpoints that use imit
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4883

UPS-4883 max limit

---

projects/uitpas/reference/uitpas.json

-  added format query param to QR download link endpoint
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4849

UPS-4849 added format query param

---

projects/uitdatabank/models/permission.json
projects/uitdatabank/reference/entry.json

- Added places/events/organizers permissions endpoints
---
Ticket: https://jira.publiq.be/browse/III-5055 and https://jira.publiq.be/browse/III-5056

Added places and events permissions endpoints

---

projects/uitdatabank/docs/search-api/advanced/boosting.md

fix dead link

---

projects/uitdatabank/reference/entry.json

- Fixed incorrect tag on endpoint
---
Ticket: https://jira.publiq.be/browse/III-5056

Fixed incorrect tag on endpoint

---

projects/uitpas/reference/uitpas.json

- Retrieve total points of a passholder by chip number
Ticket: https://jira.uitdatabank.be/browse/UPS-5283

UPS-5283 Retrieve total points of a passholder by chip number

---

projects/api-design-guidelines/docs/authentication.md
projects/uitpas/reference/uitpas.json

- added event settings api
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5250

UPS-4250 event settings api

---

.github/CODEOWNERS

- `CODEOWNERS`: Added Koen for UiTDatabank & removed Corneel for UiTDatabank
---

Offboard Corneel onboard Koen

---

projects/uitdatabank/models/common-priceInfo.json

-  `common-priceInfo.json`: Improved description of `groupPrice`
---
Ticket: https://jira.publiq.be/browse/III-6581

III-6581 improve description group price

---

projects/uitpas/reference/uitpas.json

- return error when postalcode not part of cardsystem
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5520

UPS-5520 return error when postalcode not part of cardsystem

---

projects/uitpas/reference/uitpas.json

- registrationSocialTariffEndDate in passholder registration
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5527

UPS-5527 added registrationSocialTariffEndDate

---

projects/uitdatabank/models/event-labels-put.json
projects/uitdatabank/models/place-labels-put.json
projects/uitdatabank/reference/entry.json

- Added docs for endpoints to update labels on a place or an event in bulk
---
Ticket: https://jira.uitdatabank.be/browse/III-6634

III-6634 bulk update labels

---

projects/uitdatabank/reference/entry.json

- Made bulk update labels internal
---
Ticket: https://jira.uitdatabank.be/browse/III-6634

III-6634 Make bulk update labels internal

---

projects/uitdatabank/models/event-labels-put.json
projects/uitdatabank/models/place-labels-put.json

-  Make labels optional (allow 0 labels in put)
Tested this by copy-pasting the config changes in the UDB3-backend code.
---
Ticket: https://jira.uitdatabank.be/browse/III-6634

III-6634 Make labels optional (allow 0 labels in put)

---

projects/uitpas/reference/uitpas.json

- added uitidId in passholder model
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5605

UPS-5605 added uitidId in passholder model

---

projects/uitpas/reference/uitpas.json

- fix validation
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5091

UPS-5091 fix validation

---

projects/widgets/docs/inleiding.md

- `projects/widgets/docs/inleiding.md`: remove info about Widgets Plus Plan
---
Ticket: https://jira.publiq.be/browse/PPF-691

PPF-691: remove info about Widgets Plus Plan

---

projects/uitdatabank/docs/entry-api/events/create-school.md
projects/uitdatabank/docs/entry-api/organizers/school-organizer.md

- `create-school.md`: Processed some extra feedback from Eva.
- `school-organizer.md`: Processed some extra feedback from Eva.
---
Ticket: https://jira.publiq.be/browse/III-6656

III-6656 Additional feedback

---

projects/uitdatabank/docs/search-api/filters/default-filters.md

- `default-filter.md`: Clarify documentation about searching for `DRAFT`.
---
Ticket: https://jira.publiq.be/browse/III-6716

III-6716 Clarify Docs about searching DRAFTS

---

projects/uitpas/reference/uitpas.json

- social tariff export endpoint
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5676

UPS-5676 social tariff export endpoint
