cultuurnet/apidocs

projects/uitdatabank/docs/errors.md
- Added custom `invalid-workflow-status-transition` error type for workflowStatus transitions that are not supported. (Needed in III-4689 to return a correct error response when trying to publish a rejected or deleted offer)
---
Ticket: https://jira.uitdatabank.be/browse/III-4689
=> III-4689 Add custom `invalid-workflow-status-transition` error type

projects/uitdatabank/docs/terminology.md
- Added starting point for terminology page. Can always be tweaked/expanded later when needed.
---
Preview: https://docs.publiq.be/docs/uitdatabank/branches/uitdatabank%2Fterminology/76b7bd22f7f51-terminology#nil-location (login required)
=> Add starting point for terminology page

projects/uitdatabank/reference/entry.json
- Added missing `videos` to event create/update examples
- Grouped `status` and `bookingAvailability` together in event and place update examples because they have a high cohesion functionally
- Removed `status` and `bookingAvailability` from event/place create examples because they are usually not used when creating events/places, but only set later (see ticket description)
- Removed `availableTo` from event/place create & update examples, because it's a read-only property that gets derived from the calendar info. So it is not useful to include it in create/update requests.
---
Ticket: https://jira.uitdatabank.be/browse/III-4761 + https://jira.uitdatabank.be/browse/III-4762
=> III-4761 + III-4762 Event/place example tweaks

projects/uitdatabank/reference/entry.json
- Removed `status` and `bookingAvailability` from `subEvent` in event create example
- Removed `id` from `subEvent` in event create/update examples (not necessary, derived from the position in the array and only required on the PATCH endpoint for subEvents)
- Removed `startDate` and `endDate` from event in create/update examples (these are derived from the subEvent)
- Changed `status` and `bookingAvailability` from `Available` to `Unavailable` in update examples (as that is more usual than updating it to `Available`, especially if a reason is given)
---
Follow-up PR for ticket: https://jira.uitdatabank.be/browse/III-4761
=> III-4761 Event create/update example tweaks

projects/api-design-guidelines/docs/rest.md
- Fixed 2 dead links due to refactoring of ietf.org URLs
=> Fix dead links to IETF web pages

projects/authentication/docs/introduction.md, projects/authentication/docs/requesting-credentials.md, projects/authentication/toc.json
- Introduction page
- How to get client credentials
---
Ticket: https://jira.uitdatabank.be/browse/API-88
Note: This PR only focuses on the scope described above. Other improvements to the authentication documentation are coming in different tickets / PRs.
Preview: https://docs.publiq.be/docs/authentication/branches/authentication%2FAPI-88-getting-started/d6a8ba3f3c186-introduction (login with apidocs@publiq.be user required)
=> API-88 Document how to get client credentials

projects/authentication/docs/client-access-token.md, projects/authentication/docs/client-identification.md, projects/authentication/docs/user-access-token.md
- List of requirements per authentication method
- Changes in structure of the pages for the different authentication methods, to accomodate the requirements sections
- Reworded some small parts and/or removed outdated info (like that frontend apps should always use the `?clientId` url param instead of the `x-client-id` header, or that an "Allowed origin (CORS)" is required for PKCE flow)
---
Ticket: https://jira.uitdatabank.be/browse/API-54
Note: I will make some bigger improvements to the guides for the different authentication methods in other PRs, this one just focuses on documenting the requirements on each page.
Preview branch (then navigate to the specific guides per auth method): https://docs.publiq.be/docs/authentication/branches/authentication%2FAPI-54-requirements-per-method/d6a …
=> API-54 Document requirements per authentication method

.github/CODEOWNERS
- Added @corneelwille , @JonasVHG and @JurgenG as code owners of the authentication docs
- Removed @erwin1 as code owner from the authentication docs to avoid too much noise from PRs not relevant for him. We will ping him if a specific PR requires his input
=> Update CODEOWNERS of authentication docs

projects/authentication/docs/methods.md
- Removed token expiration details from the auth methods overview page, as this is described better on the pages for the specific methods
- User access tokens can be renewed without letting the user login again
---
Ticket: https://jira.uitdatabank.be/browse/API-91
=> API-91 Remove expiration info from authentication methods overview

projects/authentication/docs/user-access-token.md
- Added an overview of all the possible URL parameters for `/authorize`
---
Ticket: https://jira.uitdatabank.be/browse/API-79
=> API-79 Document `/authorize` parameters

projects/authentication/docs/client-access-token.md, projects/authentication/docs/user-access-token.md
- Documentation how to get user info
- Removed mention of the `profile` scope which is not reliable in our case as the OpenID profile fields are apparently only filled in for social media users
---
Ticket: https://jira.uitdatabank.be/browse/API-40
=> API-40 Document how to get user info

projects/uitdatabank/docs/errors.md
- New error type in UiTdatabank docs for when an event has UiTPAS ticket sales
---
Ticket: https://jira.uitdatabank.be/browse/III-4758
=> Document error type for when an event has UiTPAS ticket sales

projects/museumpassmusees/reference/partner-api.json, projects/uitdatabank/reference/entry.json, projects/uitpas/reference/uitpas.json
- Removed all `flows` from the `securitySchemes` in all OpenAPI files. This way the (empty) URLs are not shown, and Spectral does not complain about the OpenAPI file being invalid like it would if we kept the `clientCredentials` or `authorizationCode` flows without `authorizationUrl`, `tokenUrl`, `refreshUrl`, or `scopes`
- Mentioned the specific OAuth2 grant type (flow) in the `securitySchemes` description, so it's still clear for humans reading these docs what specific flow is used for each securityScheme using the standardized names from OAuth2.
---
Ticket: https://jira.uitdatabank.be/browse/API-99
Note: We cannot enter a concrete URL because they are different for test and production, and we can only enter one. Plus with just the URL and the grant type you cannot do the auth flow, you …
=> API-99 Fix empty OAuth2 URLs on docs.publiq.be

.remarkrc, package.json, projects/api-design-guidelines/docs/introduction.md, yarn.lock
- Running `yarn docs:lint:fix` no longer reformats the frontmatter added by Stoplight Studio (since a recent update) in a way that turns it into content.
---
Ticket: https://jira.uitdatabank.be/browse/API-100
More details: Since a recent update Stoplight Studio automatically adds some Markdown frontmatter to every new article that you create (when using "Create new article"):
```
---
stoplight-id: d6a8ba3f3c186
---
```
Running `yarn docs:lint` reports no errors on this, but when you run `yarn docs:lint:fix` it changed the frontmatter to:
```
***
```
This made the `stoplight-id` a H1 header, which we obviously don't want.
The easy workaround was to just remove the frontmatter, since the preferred way to have "pretty page URLs" is not to modify the `stoplight-id`, but to use a `slug` in the …
=> API-100 Fix `stoplight-id` frontmatter being altered by `yarn docs:lint:fix`

.github/workflows/linting-docs-fix.yml, projects/uitdatabank/docs/entry-api/requirements-before-going-live.md
- Fixed the CI checks not being triggered automatically after running the job to fix linting issues in the docs
---
Ticket: https://jira.uitdatabank.be/browse/API-104
=> API-104 Fix workflows not being triggered after running the docs fixer

.github/CODEOWNERS
- Removed @Stiksels as owner of the museumPASSmusées API docs now that @DizzyMissLizzy has token over as project manager of museumPASSmusées
=> Remove Stan as owner of museumPASSmusées API docs

.github/actions/stoplight-push/action.yml
- Fixed `main` not being deployed to `unreleased` because it will always have 0 changed files compared to `main`
=> Fix `main` not being deployed to `unreleased`

projects/uitdatabank/docs/search-api/sorting.md
- Replaced "geo distance" with "coordinates" and "distance". The "geo distance" was copied from the old docs and put between backticks instead of the link that it was to a guide to searching by coordinates & distance (which does not exist in the new docs right now). But backticks indicate that it's a technical property/parameter/option/... while it does not exist.
---
I just happened to notice this while linking to this for someone who had a question about searching by distance
=> Replace "geo distance" with "coordinates" and "distance"

projects/uitdatabank/models/common-workflowStatus-offer.json, projects/uitdatabank/models/event-workflowStatus-put.json, projects/uitdatabank/models/place-workflowStatus-put.json
- Added a JSON schema for a new endpoint to update an event's/place's workflowStatus (as an alternative to the PATCH endpoint that uses custom content-types to determine the intended state transition, which is quirky). The endpoint itself will be documented later in https://jira.uitdatabank.be/browse/III-5106
---
Ticket: https://jira.uitdatabank.be/browse/III-4272
=> UiTdatabank III-4272: JSON schema for endpoint to update `workflowStatus`

projects/uitdatabank/docs/search-api/embedding.md
The calendar summary examples, so that 
* it is in line with the new calendar summary 
* the same event is used in the different examples (just different formats)
Ticket: https://jira.uitdatabank.be/browse/III-5105
=> Update calendar summary examples

projects/uitdatabank/reference/search.json
- Added missing `locationLabels` URL parameter to `GET /events` and `GET /offers`
- Added missing `organizerLabels` URL parameter to `GET /events`, `GET /places` and `GET /offers`
=> UiTdatabank: Document missing SAPI3 locationLabels and organizerLabels URL parameters

projects/uitdatabank/reference/taxonomy.json
- Removed Taxonomy API test URL. This is only used for internal purposes (to test deployments before pushing them to the production URL). And the documentation already mentions "The taxonomy API only has one environment, the production environment. Since the taxonomy terms are the same on all environments, you can also connect to this environment from your testing environment to retrieve taxonomy terms." So having a test URL in the OpenAPI documentation is confusing in that case.
=> UiTdatabank: Remove Taxonomy API test URL

.github/actions/stoplight-push/action.yml, .github/workflows/linting-docs-fix.yml, .github/workflows/linting-docs.yml, .github/workflows/linting-openapi.yml, .github/workflows/split-udb3-json-schemas.yml, projects/uitdatabank/docs/search-api/embedding.md
- Update checkout action to v3 to get rid of GitHub deprecation warnings for NodeJS 12.
=> Update checkout action to v3

projects/uitdatabank/reference/search.json
- Added an example to clarify the autocomplete behaviour in SAPI3 organizers `name` parameter
=> Clarify autocomplete behaviour in SAPI3 organizers `name` parameter

projects/uitdatabank/docs/search-api/advanced-queries.md, projects/uitdatabank/toc.json
- Added a little bit more context in the "Advanced queries" guide
- Changed the order of SAPI3 guides and split them up in "Getting started" and "Advanced features", so we can add something like "Common search scenario's" in a later PR with guides like "Searching by location", "Searching by date(s)", etc.
- Minor fixes / tweaks
=> UiTdatabank: "Advanced queries" guide tweaks

projects/uitdatabank/models/event-description-put.json, projects/uitdatabank/models/place-description-put.json
- Allow the description to be an empty string when updating an offer.
---
Ticket: https://jira.uitdatabank.be/browse/III-4251
=> Uitdatabank - fix offer empty description put

projects/uitdatabank/reference/entry.json
- Documentation for PUT `/events/{eventId}/images/{imageId}`
- Documentation for PUT /places/{placeId}/images/{imageId}`
---
Ticket: https://jira.uitdatabank.be/browse/III-5049
=> Uitdatabank - offer image put

projects/uitdatabank/reference/entry.json
You can double check the documentation [here](https://docs.publiq.be/docs/uitdatabank/branches/uitdatabank%2FIII-5100-post-images/1d9b45cbc812b-image-create)
- Documentation for POST `/images`
---
Ticket: https://jira.uitdatabank.be/browse/III-5100
=> Uitdatabank - images post

projects/uitdatabank/models/event-@id.json, projects/uitdatabank/models/event-attendanceMode-put.json, projects/uitdatabank/models/organizer-@id.json, projects/uitdatabank/models/place-@id.json, projects/uitdatabank/reference/entry.json
- Fixed the `location` property being hidden on the "attendanceMode - update" endpoint documentation. This was caused by the referenced `place.@id` being `readOnly`.
---
Ticket: https://jira.uitdatabank.be/browse/III-5162
=> III-5162 Document location on attendanceMode update endpoint

projects/authentication/docs/client-access-token.md, projects/authentication/docs/methods.md, projects/authentication/docs/user-access-token.md, projects/authentication/toc.json, projects/uitdatabank/reference/entry.json, projects/uitdatabank/reference/search.json, projects/uitpas/docs/registering-events.md, projects/uitpas/reference/uitpas.json
- Fixed casing of UiTiD in all occurrences where it was incorrectly written as UiTID
---
This seems like a mistake that a lot of people (including me) make. (I also see it a lot in other communication from colleagues). I just happened to notice at some point that it's actually supposed to be UiTiD.
See for example the casing in the logo: 
On the helpdesk website: https://helpdesk.uitid.be/hc/nl-be
And on https://profile.uitid.be/nl/home (for example in the title of the window/tab), "Vragen over UiTiD?", etc.
=> Fix casing of UiTiD

projects/uitdatabank/docs/terminology.md
- Changed all `h3` titles in the terminology page to `h2` titles. I initially used h3's to make some concepts children of others (like "Online event" as a child of "Event"), but the structure just got confusing to read IMHO now that I re-read it myself after a while. It's probably better to put every concept on the same level and order them logically and refer to others where needed.
---
Ticket: https://jira.uitdatabank.be/browse/III-5180
=> III-5180 Make all terminology entries h2

.remarkrc, projects/uitdatabank/docs/introduction.md
- Replaced link to `overheid.vlaanderen.be` about API of the year award (2019) that is suddenly dead
=> UiTdatabank: Replace dead link

projects/_template/reference/example-api.json, projects/authentication/docs/cors.md, projects/authentication/docs/requesting-credentials.md, projects/museumpassmusees/reference/partner-api.json, projects/uitdatabank/docs/entry-api/requirements-before-going-live.md, projects/uitdatabank/docs/taxonomy-api/terms.md, projects/uitdatabank/reference/entry.json, projects/uitdatabank/reference/search.json, projects/uitdatabank/reference/taxonomy.json, projects/uitpas/reference/uitpas.json
- Updated contact email address in the OpenAPI files
- Added missing link to contact info on CORS page
- Replaced vragen@publiq.be links with link to landing page with contact info
- Replaced vragen@publiq.be email address to use facility terms with partnerships@publiq.be
---
Ticket: https://jira.uitdatabank.be/browse/API-19
Note: Some pages still contain direct links to the email addresses partnerships@publiq.be and content.cultuurkuur@publiq.be for specific messages not related to technical issues/questions. To be discussed if we also replace those with links to the landing page (if we also mention those there)
=> API-19 Update contact info

projects/widgets/docs/configureren/starten-met-configureren.md, projects/widgets/toc.json
- Fixed slug of "Starten met configureren" page
- Fixed broken links to other "configureren" pages on "Starten met configureren"
- Fixed typo in "Verfijningen" link
=> Widgets links fixes

projects/authentication/docs/methods.md
- On the overview of authentication methods per API, link to the introduction pages of the UiTdatabank APIs instead of their OpenAPI detail page
=> Authentication: Use links to introduction pages of UiTdatabank APIs

projects/uitpas/docs/registering-ticket-sales-group.md, projects/uitpas/docs/registering-ticket-sales-multiple.md, projects/uitpas/docs/registering-ticket-sales.md
- Fixed various broken links in the UiTPAS guides. Not sure yet why these were not detected by the dead link checker. I also noticed it in the Widgets/UiTdatabank documentation sometimes, so it's not a unique problem.
---
You can check the links on the Stable version on Stoplight to see that they lead to 404s
=> Fix broken links in UiTPAS guides

projects/uitdatabank/docs/entry-api/events/copy.md, projects/uitdatabank/toc.json
- Removed "Copying an existing event" page, because the relevant endpoint is marked as internal
---
=> III-5108 Remove "copying an event" page

projects/uitdatabank/docs/entry-api/events/create-online.md, projects/uitdatabank/docs/entry-api/events/create-school.md, projects/uitdatabank/docs/entry-api/events/create-uitpas.md
- Minor changes to the school events guide, like adding a link to the guide about creating new events to read that first, adding some info about permissions, and some other minor additions/tweaks.
- Obsolete "target group" and "subject" labels
- Fixed very small typo in the UiTPAS events guide and copied the new wording to the school events & online events guides
---
=> III-5108 School events tweaks

projects/uitdatabank/docs/entry-api/events/create-online.md, projects/uitdatabank/docs/entry-api/events/create-uitpas.md, projects/uitdatabank/docs/entry-api/events/create.md, projects/uitdatabank/docs/search-api/getting-started.md
- Changed absolute URLs to endpoints in OpenAPI files with relative ones. Stoplight will automatically "prettify" these like links to `.md` files.
---
Note: There is actually an issue with these links, because links that start with `/` are not checked by the dead link checker for some reason. But also, in theory this is not a valid path because everything after the `.json` does not exist on the file system, so the dead linker checker would complain about them. So in this case it's useful, but should be improved to actually check that the link works. I've created a  ticket for that: https://jira.uitdatabank.be/browse/API-116
In the meantime I've replaced the links to this format because other docs like UiTPAS also do it like this. So then …
=> III-5108 Replace absolute URLs to OpenAPI endpoints with relative ones

projects/uitpas/reference/uitpas.json
- Java code generation tools expect explicit type for arrays
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4374
=> UPS-4374 specify string type for new array params

projects/uitdatabank/models/common-string-uri-video.json
- Update `regex` for `video-urls` to allow embedded `YouTube`-url eg. `https://www.youtube.com/embed/yi_XlQetN28`
---
Ticket: https://jira.uitdatabank.be/browse/III-5428
=> III-5428 update video url regex

.github/CODEOWNERS
- Updated the default code owners, and the code owners per project, so that there are at least 2 owners per project & for files not specific to one project
- Removed @bertramakers from `CODEOWNERS`
=> Simplify CODEOWNERS and remove @bertramakers

projects/authentication/docs/methods.md, projects/uitdatabank/docs/search-api/authentication.md
- Marked client access tokens & user access tokens as usable on Search API v3
---
Ticket: https://jira.uitdatabank.be/browse/API-122
=> API-122 Mark client tokens & user tokens as usable on Search API v3

projects/uitdatabank/models/common-string-uri.json
- Changed regex for `common-string-uri`
- Catch triple Slashed Uri's(e.g., `https:///publiq.be`)
---
Ticket: https://jira.uitdatabank.be/browse/III-5581
=> III-5581 update regex url to catch triple slashes

projects/uitpas/reference/uitpas.json
- include redundant uitpas number in passholder
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4380
=> UPS-4380 include redundant uitpas number in passholder

projects/uitdatabank/models/production.json, projects/uitdatabank/reference/entry.json
- Use correct `JsonBody` for `productions`
- (Decide how to resolve camelCase vs. existing `production_id`)
- API uses both depracted snake_case `production_id` and camleCase `productionId`. Only `productionId` will be used in the docs.
---
Ticket: https://jira.uitdatabank.be/browse/III-5556
=> Uitdatabank/III-5556 Get productions Json Corrections

projects/uitdatabank/models/common-string-uri.json
- `common-string-uri.json`: updated regex
- Url's with `#` are now allowed
---
Ticket: https://jira.uitdatabank.be/browse/III-5712
=> III-5712 allow hashes in uri regex

projects/uitdatabank/docs/terminology.md
- Dead url for Erfgoedcel Leuven
=> Fix dead url of Erfgoecel Leuven

projects/uitdatabank/reference/entry.json
- Use `POST` instead `PUT` for merging `productions`
---
Ticket: https://jira.uitdatabank.be/browse/III-5822
=> III-5822 use correct method name for merging productions

.remarkrc
- Added `api.publiq.be` to links to ignore, because it is a redirect and used in API responses.
- Linting is `green` again
---
=> Projects: Ignore api Links

projects/uitdatabank/reference/search.json
- Incorrect sentence about the `worfklowStatus` parameter being applicable on the /organizers endpoint
You can check the output here now: https://docs.publiq.be/docs/uitdatabank/branches/uitdatabank%2Ffix-search-organizers/search-api/reference/operations/list-organizers
=> Remove incorrect sentence about the `workflowStatus` parameter

projects/uitdatabank/reference/entry.json
- Set contributor docs to `internal`
---
Ticket: https://jira.uitdatabank.be/browse/III-6054
=> Set contributor docs to internal

README.md, projects/uitdatabank/docs/errors.md, projects/uitdatabank/reference/entry.json
There is now a duplicate places check when creating a place.
This throws a 409 status code. 
This PR documents the new error.
Related to: https://github.com/cultuurnet/udb3-backend/pull/1600
---
Ticket: https://jira.uitdatabank.be/browse/III-4601
=> III-4601 - Added 409 status to Places

projects/uitdatabank/docs/entry-api/events/publish.md, projects/uitdatabank/docs/search-api/advanced/advanced-queries.md
- `uitdatabank/docs/entry-api/events/publish.md`: Update info about `Types` that are available till start(e.g., camping)
- `uitdatabank/docs/entry-api/events/publish.md`: Update info about `Camping` that is available till startDate.
---
Ticket: https://jira.publiq.be/browse/III-6034
=> III-6034 update info about availalbeTo for Camping Events

projects/uitdatabank/docs/entry-api/shared/labels.md
- In the current documentation page about labels it is not very clear if you can delete _all_ labels from an event or not.
- On other pages like https://docs.publiq.be/docs/uitdatabank/entry-api%2Freference%2Foperations%2Fupdate-a-event we already had an alert about labels being kept on the event after an update.
This PR adds this alert to the label documentation page
- Add alert
- Typo
---
=> Add alert about label exception

projects/uitdatabank/toc.json
- Link to contributors docs from side bar
Actual documentation page remains (for now) but with the changes from this PR you won't be able to navigate to the page using the sidebar 
---
Ticket: https://jira.uitdatabank.be/browse/III-6054
=> Remove link to shared contributors page from side bar

projects/uitdatabank/models/ownership-post.json, projects/uitdatabank/reference/entry.json
- Add docs for the endpoint to request ownership
- These docs are internal and still work in progress, most important part is the JSON schema that can be used by `udb3-backend` to do the simple field validation
---
Ticket: https://jira.uitdatabank.be/browse/III-6069
=> III-6069 request ownership

projects/uitdatabank/docs/errors.md, projects/uitdatabank/reference/entry.json
- Added a new internal endpoint to subscribe to a newsletter
- Added a new error that can happen if newsletter subscription failed 
Read the docs: https://docs.publiq.be/docs/uitdatabank/branches/III-6147%2Fnew-mail-subscription-endpoint/entry-api/reference/operations/update-a-mailinglist
---
Ticket: https://jira.uitdatabank.be/browse/III-6147
=> III-6147 New internal endpoint - subscribe to newsletter

projects/uitdatabank/docs/entry-api/events/create-school.md
- `create-school`: Use the correct contact-email for `CultuurKuur`
---
=> use correct email for cultuurkuur

projects/uitdatabank/models/common-string-uri-image.json
- Allowed encoded space for the image URL of a news article. Only an encoded space is allowed to not interfere with the `Url` value object validation in `udb3-backed`
- Related pull request https://github.com/cultuurnet/udb3-backend/pull/1864
---
Ticket: https://jira.uitdatabank.be/browse/III-6312
=> III-6312 Allow encoded space

projects/uitpas/reference/uitpas.json
- UPS-5065 better re-use of permission enums
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5065
=> UPS-5065 better re-use of permission enums

projects/uitpas/reference/uitpas.json
- add cardStatus to grouppass
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5304
=> UPS-5304 add cardStatus to grouppass

projects/uitdatabank/reference/entry.json
- Add 2 new internal endpoints, /regions and /educational-levels, meant for the new Cultuurkuur flow
- https://github.com/cultuurnet/udb3-backend/pull/2047
---
Ticket: https://jira.uitdatabank.be/browse/III-6579
=> III-6579 Endpoint municipalities and education levels

projects/uitdatabank/models/common-labels-optional.json, projects/uitdatabank/models/event-labels-put.json, projects/uitdatabank/models/place-labels-put.json
- I must have done something wrong with my previous PR because it turns out to not work. :-( this new approach does. sorry!
---
Ticket: https://jira.uitdatabank.be/browse/III-6634
=> III-6634 New approach to make labels optional

projects/uitdatabank/reference/entry.json, projects/uitdatabank/reference/search.json
- `projects/uitdatabank/reference/entry.json`: Don't make `errors` internal.
- `projects/uitdatabank/reference/search.json`: Don't make `errors` internal.
- Anonymous users should no longer see an error, when they want to see the response body for `4XX`
---
Ticket: https://jira.publiq.be/browse/III-6733
=> III-6733 Error response body not working for anonymous users
